<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "leadinfo"
 *
 * Auto generated by Extension Builder 2021-09-13
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Leadinfo',
    'description' => 'Leadinfo enables you to see real-time which companies are visiting your website and what pages they’re viewing to increase your sales.',
    'category' => 'plugin',
    'author' => 'Leadinfo',
    'author_email' => 'integrations@leadinfo.com',
    'state' => 'stable',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.2',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-11.9.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
